version: "3.9"

services:
  app:
    image: 426315020355.dkr.ecr.ap-south-1.amazonaws.com/securevault:v3
    container_name: securevault-app
    ports:
      - "4000:4000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-1.czgsmga2siiz.ap-south-1.rds.amazonaws.com:5432/securevaultdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=vaultkey2419
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - SPRING_DATA_MONGODB_DATABASE=${SPRING_DATA_MONGODB_DATABASE}
      - SPRING_DATA_REDIS_HOST=securevault-redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: securevault-redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: securevault-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
