services:
  db:
    image: postgres:15
    container_name: securevault-db
    environment:
      - POSTGRES_DB=securevault_db
      - POSTGRES_USER=amansharma
      - POSTGRES_PASSWORD=aman2319
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: securevault-app
    ports:
      - "4000:4000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/securevault_db
      - SPRING_DATASOURCE_USERNAME=amansharma
      - SPRING_DATASOURCE_PASSWORD=aman2319
      - SPRING_DATA_MONGODB_URI=mongodb+srv://flaman:FlutterDev@2419@securevaultai.mx0qhvx.mongodb.net?retryWrites=true&w=majority
      - SPRING_DATA_MONGODB_DATABASE=secure_vault
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    container_name: securevault-redis
    
    ports:
      - "6379:6379"
  nginx:
    image: nginx:latest
    container_name: securevault-nginx
    ports:
      - "80:80"        # Nginx accessible on localhost:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  postgres_data:
